//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientGateway_ShippingConfirmation
    {
        public int id { get; set; }
        public int ClientGateway_Id { get; set; }
        public string Confirmation_Url { get; set; }
        public string ConfirmationType { get; set; }
        public string SMTPServer { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Port { get; set; }
        public string ContentType { get; set; }
        public string HtmlText { get; set; }
        public bool PostageRequired { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Client_Gateway Client_Gateway { get; set; }
    }
}
