//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientGateway_CarrierService
    {
        public int id { get; set; }
        public int ClientGateway_Id { get; set; }
        public string ShippingMethod { get; set; }
        public int CarrierService_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool Enabled { get; set; }
        public string Comments { get; set; }
    
        public virtual Carrier_Service Carrier_Service { get; set; }
        public virtual Client_Gateway Client_Gateway { get; set; }
    }
}
