//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Gateway
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_Gateway()
        {
            this.ClientGateway_ShippingConfirmation = new HashSet<ClientGateway_ShippingConfirmation>();
            this.ClientGateway_CarrierService = new HashSet<ClientGateway_CarrierService>();
            this.Orders = new HashSet<Order>();
            this.Product_SKU = new HashSet<Product_SKU>();
        }
    
        public int id { get; set; }
        public Nullable<System.Guid> Data_identifier { get; set; }
        public int Gateway_Id { get; set; }
        public int Client_Id { get; set; }
        public string GatewayUserId { get; set; }
        public string StoreKey { get; set; }
        public string AccessToken { get; set; }
        public string GatewayPassword { get; set; }
        public Nullable<int> OrderDownloadType { get; set; }
        public int OrderDownloadDays { get; set; }
        public string SecurityProtocol { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientGateway_ShippingConfirmation> ClientGateway_ShippingConfirmation { get; set; }
        public virtual Gateway Gateway { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientGateway_CarrierService> ClientGateway_CarrierService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_SKU> Product_SKU { get; set; }
    }
}
