//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Company_Domain_Object = new HashSet<Company_Domain_Object>();
            this.Partner_Company = new HashSet<Partner_Company>();
        }
    
        public int id { get; set; }
        public int CompanyType_Id { get; set; }
        public int Address_Id { get; set; }
        public int Contact_Id { get; set; }
        public Nullable<int> PaymentTerms_Id { get; set; }
        public string AccountId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Web_Url { get; set; }
        public Nullable<System.Guid> Data_Identifier { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company_Type Company_Type { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Domain_Object> Company_Domain_Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_Company> Partner_Company { get; set; }
        public virtual Payment_Terms Payment_Terms { get; set; }
    }
}
