//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransaction_Log
    {
        public int id { get; set; }
        public int InventoryLocation_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> OpeningQuantity { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> OrderItem_ID { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Inventory_Location Inventory_Location { get; set; }
        public virtual Order_Item Order_Item { get; set; }
    }
}
