//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Details
    {
        public int id { get; set; }
        public int Client_Id { get; set; }
        public int Order_Id { get; set; }
        public string ReferenceId { get; set; }
        public int Invoice_Id { get; set; }
        public string ReferObject { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool Invoiced { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Order Order { get; set; }
    }
}
