//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Item()
        {
            this.InventoryTransaction_Log = new HashSet<InventoryTransaction_Log>();
            this.Order_Item_Location = new HashSet<Order_Item_Location>();
            this.Package_Item = new HashSet<Package_Item>();
        }
    
        public int id { get; set; }
        public int Order_Id { get; set; }
        public int Product_Id { get; set; }
        public int Quantity { get; set; }
        public int Status_Id { get; set; }
        public int ShippingInfo_Id { get; set; }
        public int Warehouse_Id { get; set; }
        public int ProductSku_Id { get; set; }
        public Nullable<bool> CopyProtection { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Bom_Id { get; set; }
        public string BomDynamic_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransaction_Log> InventoryTransaction_Log { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item_Location> Order_Item_Location { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product_SKU Product_SKU { get; set; }
        public virtual Shipping_Info Shipping_Info { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Item> Package_Item { get; set; }
    }
}
