//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Invoice_Details = new HashSet<Invoice_Details>();
            this.Order_Item = new HashSet<Order_Item>();
            this.Order_Queue = new HashSet<Order_Queue>();
            this.Returns = new HashSet<Return>();
            this.Shipping_Info = new HashSet<Shipping_Info>();
        }
    
        public int id { get; set; }
        public Nullable<System.Guid> Data_identifier { get; set; }
        public int ClientGateway_Id { get; set; }
        public int Status_Id { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> ClientShop_Id { get; set; }
        public string AdditionalPONumber { get; set; }
        public int Invoice_Id { get; set; }
        public Nullable<bool> FulFillFlag { get; set; }
        public string UpdateStatusReason { get; set; }
        public Nullable<int> ShipmentConfirmation { get; set; }
        public Nullable<bool> UseShopAccount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Client_Gateway Client_Gateway { get; set; }
        public virtual Client_Shop Client_Shop { get; set; }
        public virtual Invoice Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Details> Invoice_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Queue> Order_Queue { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return> Returns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping_Info> Shipping_Info { get; set; }
    }
}
