//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item_Location
    {
        public int id { get; set; }
        public int OrderItem_Id { get; set; }
        public int InventoryLocation_Id { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Inventory_Location Inventory_Location { get; set; }
        public virtual Order_Item Order_Item { get; set; }
    }
}
