//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Queue
    {
        public int id { get; set; }
        public int Order_Id { get; set; }
        public int Warehouse_Id { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
