//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageItem_Serialnumber
    {
        public int id { get; set; }
        public int PackageItem_Id { get; set; }
        public string Serialnumber { get; set; }
        public Nullable<bool> IsReturned { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Package_Item Package_Item { get; set; }
    }
}
