//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pack_Discount
    {
        public int id { get; set; }
        public int Fee_Id { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Fee Fee { get; set; }
    }
}
