//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Shipping
    {
        public int id { get; set; }
        public int Package_Id { get; set; }
        public int Shipping_Id { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<decimal> PackageShipping_Cost { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
