//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_SKU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_SKU()
        {
            this.Order_Item = new HashSet<Order_Item>();
        }
    
        public int id { get; set; }
        public int Product_Id { get; set; }
        public int ClientGateway_Id { get; set; }
        public string SKU { get; set; }
        public int Bundle_Id { get; set; }
        public Nullable<int> Bundle_Quantity { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual Bundle Bundle { get; set; }
        public virtual Client_Gateway Client_Gateway { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        public virtual Product Product { get; set; }
    }
}
