//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return
    {
        public int id { get; set; }
        public int ReturnAction_Id { get; set; }
        public int Order_Id { get; set; }
        public int ReturnCondition_Id { get; set; }
        public string Reason { get; set; }
        public int Product_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ReferenceNumber { get; set; }
        public int User_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Return_Action Return_Action { get; set; }
        public virtual Return_Condition Return_Condition { get; set; }
        public virtual User User { get; set; }
    }
}
