//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_Discount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipping_Discount()
        {
            this.Client_Shipping_Discount = new HashSet<Client_Shipping_Discount>();
        }
    
        public int id { get; set; }
        public int CarrierService_Id { get; set; }
        public int ShippingZone_Id { get; set; }
        public int UnitOfMeasure_Id { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<double> Discount { get; set; }
        public int DiscountType_Id { get; set; }
        public Nullable<double> DiscountLimit { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Carrier_Service Carrier_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Shipping_Discount> Client_Shipping_Discount { get; set; }
        public virtual Discount_Type Discount_Type { get; set; }
        public virtual ShippingZone ShippingZone { get; set; }
        public virtual Unit_Of_Measure Unit_Of_Measure { get; set; }
    }
}
