//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipping()
        {
            this.Package_Shipping = new HashSet<Package_Shipping>();
        }
    
        public int id { get; set; }
        public int Shipment_Id { get; set; }
        public Nullable<bool> LabelStatus { get; set; }
        public Nullable<int> LabelStatus_Code { get; set; }
        public string LabelStatusReason { get; set; }
        public int User_Id { get; set; }
        public int Shipped_CarrierServiceId { get; set; }
        public Nullable<decimal> Shipping_Cost { get; set; }
        public int ClientShippingDiscount_Id { get; set; }
        public Nullable<decimal> Actual_Cost { get; set; }
        public int ShippingZone_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Carrier_Service Carrier_Service { get; set; }
        public virtual Client_Shipping_Discount Client_Shipping_Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Shipping> Package_Shipping { get; set; }
        public virtual Shipping_Info Shipping_Info { get; set; }
        public virtual ShippingZone ShippingZone { get; set; }
        public virtual User User { get; set; }
    }
}
