//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipping_Info()
        {
            this.Order_Item = new HashSet<Order_Item>();
            this.Shipments = new HashSet<Shipment>();
            this.Shippings = new HashSet<Shipping>();
        }
    
        public int id { get; set; }
        public int Order_Id { get; set; }
        public int Address_Id { get; set; }
        public int Contact_Id { get; set; }
        public int CarrierService_Id { get; set; }
        public string AmazonShipment_Id { get; set; }
        public Nullable<bool> SignatureConfirmation { get; set; }
        public Nullable<bool> SaturdayDelivery { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ShipDynamic_Id { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Carrier_Service Carrier_Service { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping> Shippings { get; set; }
    }
}
