//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Acutrack.Fulfillment
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Country_Id { get; set; }
        public Nullable<bool> IsTerritory { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
